// Re-export de lib/db/index.ts para compatibilidad con imports existentes.
// Las funciones reales viven en lib/db/ (partidas por dominio).
export {
  db,
  votesDb,
  getUpcomingFixtures,
  getFixtureById,
  getRecentFixtures,
  getFixturesByJornada,
  getFixturesInRange,
  getRecentFinishedWithPredictions,
  getAllTeams,
  getTeamById,
  getTeamRecentFixtures,
  getTeamUpcomingFixtures,
  getLatestPredictionForFixture,
  getPredictionView,
  getPredictionHistory,
  getMatchdayOrdinal,
  getMatchdayOrdinalByDate,
  getMatchdayLabel,
  getFixtureCounts,
  getHistoryStats,
  getCrowdSummary,
  getUserPick,
  getCrowdPick,
} from "./db/index";

export type {
  Team,
  Venue,
  Season,
  Fixture,
  FixtureWithTeams,
  FixtureDetail,
  TeamFixture,
  AnalystPrediction,
  PredictionView,
  FixtureWithPrediction,
  Outcome,
  HistoryRow,
  HistoryStats,
  CrowdSummary,
  Pick,
} from "./db/index";
